export const userTransactionsData = {
    status: 200,
    message: "Successfully got account transactions data",
    body: {
      transactions: [
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "5.00",
          balance: "2082.79",
          type: "Electronic",
          category: "sport",
          notes: "",
          transactionId: "checking1",
          updatedAt: "",
          accountId: "checking",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "10.00",
          balance: "2087.79",
          type: "Electronic",
          category: "furnitures",
          notes: "Waiting for refund",
          transactionId: "checking2",
          updatedAt: "",
          accountId: "checking",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "20.00",
          balance: "2097.79",
          type: "Electronic",
          category: "food",
          notes: "",
          transactionId: "checking3",
          updatedAt: "",
          accountId: "checking",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "30.00",
          balance: "2117.79",
          type: "Electronic",
          category: "clothes",
          notes: "",
          transactionId: "checking4",
          updatedAt: "",
          accountId: "checking",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "40.00",
          balance: "2147.79",
          type: "Electronic",
          category: "sport",
          notes: "",
          transactionId: "checking5",
          updatedAt: "",
          accountId: "checking",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "50.00",
          balance: "2187.79",
          type: "Electronic",
          category: "food",
          notes: "",
          transactionId: "checking6",
          updatedAt: "",
          accountId: "checking",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "5.00",
          balance: "2082.79",
          type: "Electronic",
          category: "sport",
          notes: "",
          transactionId: "savings1",
          updatedAt: "",
          accountId: "savings",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "10.00",
          balance: "2087.79",
          type: "Electronic",
          category: "furnitures",
          notes: "Waiting for refund",
          transactionId: "savings2",
          updatedAt: "",
          accountId: "savings",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "20.00",
          balance: "2097.79",
          type: "Electronic",
          category: "food",
          notes: "",
          transactionId: "savings3",
          updatedAt: "",
          accountId: "savings",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "30.00",
          balance: "2117.79",
          type: "Electronic",
          category: "clothes",
          notes: "",
          transactionId: "savings4",
          updatedAt: "",
          accountId: "savings",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "40.00",
          balance: "2147.79",
          type: "Electronic",
          category: "sport",
          notes: "",
          transactionId: "savings5",
          updatedAt: "",
          accountId: "savings",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "50.00",
          balance: "2187.79",
          type: "Electronic",
          category: "food",
          notes: "",
          transactionId: "savings6",
          updatedAt: "",
          accountId: "savings",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "5.00",
          balance: "2082.79",
          type: "Electronic",
          category: "sport",
          notes: "",
          transactionId: "credit-card1",
          updatedAt: "",
          accountId: "credit-card",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "10.00",
          balance: "2087.79",
          type: "Electronic",
          category: "furnitures",
          notes: "Waiting for refund",
          transactionId: "credit-card2",
          updatedAt: "",
          accountId: "credit-card",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "20.00",
          balance: "2097.79",
          type: "Electronic",
          category: "food",
          notes: "",
          transactionId: "credit-card3",
          updatedAt: "",
          accountId: "credit-card",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "30.00",
          balance: "2117.79",
          type: "Electronic",
          category: "clothes",
          notes: "",
          transactionId: "credit-card4",
          updatedAt: "",
          accountId: "credit-card",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "40.00",
          balance: "2147.79",
          type: "Electronic",
          category: "sport",
          notes: "",
          transactionId: "credit-card5",
          updatedAt: "",
          accountId: "credit-card",
        },
        {
          createdAt: "June 20th, 2020",
          description: "Golden Sun Bakery",
          amount: "50.00",
          balance: "2187.79",
          type: "Electronic",
          category: "food",
          notes: "",
          transactionId: "credit-card6",
          updatedAt: "",
          accountId: "credit-card",
        },
      ],
    },
  };